# Generated by Django 4.1 on 2023-03-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userinfodb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfodb',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
